# Generated by Django 4.2.7 on 2024-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_counted_views_posts_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='published_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
