# Generated by Django 4.2.7 on 2024-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_posts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='published_date_time',
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
